/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.diu_entrega_6;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;

/**
 *
 * @author alber
 */
public class Frame extends javax.swing.JFrame {

    static {nu.pattern.OpenCV.loadShared();}
    static {System.loadLibrary(Core.NATIVE_LIBRARY_NAME);}
    JFileChooser fc = new JFileChooser();
    FileNameExtensionFilter filtro = null;
    BufferedImage im = null;
    File fichero = null;
    Mat imgUmbralizada = null;
    
    public Frame() {
        initComponents();
        this.setTitle("Umbralizar una imagen - Jorge Marrer & Alberto Mejias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new com.mycompany.diu_entrega_6.Lienzo();
        menuBar = new javax.swing.JMenuBar();
        ficheroMenu = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        umbralizar = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        opcionesMenu = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        ficheroMenu.setMnemonic('F');
        ficheroMenu.setText("Ficheros");

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        ficheroMenu.add(abrir);

        umbralizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        umbralizar.setText("Umbralizar");
        umbralizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umbralizarActionPerformed(evt);
            }
        });
        ficheroMenu.add(umbralizar);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        ficheroMenu.add(guardar);

        menuBar.add(ficheroMenu);

        opcionesMenu.setMnemonic('O');
        opcionesMenu.setText("Opciones");

        ayuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        opcionesMenu.add(ayuda);
        opcionesMenu.add(jSeparator1);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        opcionesMenu.add(salir);

        menuBar.add(opcionesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int op = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que quiere salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_salirActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Selecciona una imagen desde el menú 'Ficheros' para visualizarla.\nPosteriormente podrá umbralizar seleccionando el valor del umbral y guardar la imagen.", "Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ayudaActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        filtro = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png");
        fc.addChoosableFileFilter(filtro);
        int op = fc.showOpenDialog(null);
        if (op == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
            imgUmbralizada = Imgcodecs.imread(fichero.getAbsolutePath());
            try {
                im = ImageIO.read(fichero);
                if (im.getWidth() > 1024 || im.getHeight() > 768) {
                    JOptionPane.showMessageDialog(rootPane, "Tamaño de la imagen mayor que 1024x768", "Imagen no permitida", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.setSize(new Dimension(im.getWidth() + 20, im.getHeight() + 60));
                    lienzo.setImagen(im);
                    this.setResizable(false);
                }
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void umbralizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umbralizarActionPerformed
        if (fichero != null) {
            String input = JOptionPane.showInputDialog(rootPane, "Escribe el valor del umbral", "Umbralizar", JOptionPane.QUESTION_MESSAGE);
            Mat imgOriginal = Imgcodecs.imread(fichero.getAbsolutePath());
            try {
                imgUmbralizada = umbralizar(imgOriginal, Integer.parseInt(input));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Debes introducir un número", "Input erróneo", JOptionPane.ERROR_MESSAGE);
            }
            BufferedImage imgUmb = (BufferedImage) HighGui.toBufferedImage(imgUmbralizada);
            lienzo.setImagen(imgUmb);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes abrir un fichero primero", "Error al umbralizar", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_umbralizarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if (fichero != null) {
            int op = fc.showSaveDialog(null);
            if (op == JFileChooser.APPROVE_OPTION) {
                if (fc.getSelectedFile().getName().equals(fichero.getName())) {
                    int dialog = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que quiere sobreescribir el archivo?", "Sobreescribir", JOptionPane.YES_NO_OPTION);
                    if (dialog == JOptionPane.YES_OPTION) {
                        Imgcodecs.imwrite(fc.getSelectedFile().getAbsolutePath(), imgUmbralizada);
                    }
                } else {
                    Imgcodecs.imwrite(fc.getSelectedFile().getAbsolutePath(), imgUmbralizada);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes abrir un fichero primero", "Error al guardar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private Mat umbralizar(Mat imagen_original, Integer umbral) {
// crear dos imágenes en niveles de gris con el mismo
// tamaño que la original
        Mat imagenGris = new Mat(imagen_original.rows(),
                imagen_original.cols(),
                CvType.CV_8U);
        Mat imagenUmbralizada = new Mat(imagen_original.rows(),
                imagen_original.cols(),
                CvType.CV_8U);
// convierte a niveles de grises la imagen original
        Imgproc.cvtColor(imagen_original,
                imagenGris,
                Imgproc.COLOR_BGR2GRAY);
// umbraliza la imagen:
// - píxeles con nivel de gris > umbral se ponen a 1
// - píxeles con nivel de gris <= umbra se ponen a 0
        Imgproc.threshold(imagenGris,
                imagenUmbralizada,
                umbral,
                255,
                Imgproc.THRESH_BINARY);
// se devuelve la imagen umbralizada
        return imagenUmbralizada;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem ayuda;
    private javax.swing.JMenu ficheroMenu;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private com.mycompany.diu_entrega_6.Lienzo lienzo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu opcionesMenu;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem umbralizar;
    // End of variables declaration//GEN-END:variables
}
